Repository codestates-seb/seb41_main_008, pull requests merged in 2023-02, with the labels that each got.

#145 feat:다크모드 구현
  client/.env
  client/src/App.tsx
  client/src/components/Card.tsx
  client/src/components/Carousel/MainCarousel.tsx
  client/src/components/Header/DropdownItems.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Modals/CartItems.tsx
  client/src/components/Modals/CartingModal.tsx
  client/src/components/Modals/SellModal.tsx
  client/src/components/Modals/TransActionModal.tsx
  client/src/components/Modals/WalletModal.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/MyCollection.tsx
  client/src/pages/ProfilePage.tsx
Labels: FrontEnd, Feat

#148 Fe/bug/#147 fix card component
  client/src/components/Card.tsx
  client/src/components/CartButton/BuyAndCartButton.tsx
  client/src/components/Modals/BuyCoinModal.tsx
  client/src/components/Modals/WalletModal.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/utils/api/api.ts
Labels: Bug, FrontEnd

#149 fix: queryFn 수정
  client/src/App.tsx
  client/src/components/CreateItem/CreateItem.tsx
  client/src/components/Header/Dropdown.tsx
  client/src/components/Header/Header.tsx
  client/src/components/ItemCard.tsx
  client/src/components/ItemDetail/ItemDetail.tsx
  client/src/components/Modals/CartItems.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/EditProfile.tsx
Labels: Bug, FrontEnd

#150 fix: carousel & collection 상세 페이지 수정
  client/src/components/Carousel/MainCarousel.tsx
  client/src/index.css
  client/src/pages/CollectionDetails.tsx
Labels: Bug, FrontEnd

#152 Fe/bug/#151 헤더바수정및아이템링크수정
  client/src/components/Card.tsx
  client/src/components/CreateItem/CreateItem.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Modals/SellModal.tsx
  client/src/pages/CollectionDetails.tsx
Labels: Bug, FrontEnd

#154 bug:다크모드 css수정
  client/src/components/Card.tsx
  client/src/components/CreateCollection/CreateCollection.tsx
  client/src/components/CreateItem/CreateItem.tsx
  client/src/components/Header/Dropdown.tsx
  client/src/components/Header/DropdownItems.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Header/MobileDropdown.tsx
  client/src/components/Header/MobileDropdownItems.tsx
  client/src/components/LoginAndSignup/InputContainer.tsx
  client/src/components/Modals/SellModal.tsx
  client/src/components/Modals/WalletModal.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/pages/MyCollection.tsx
Labels: Bug, FrontEnd

#158 Fe/feat/검색 결과 없는 경우 처리
  client/src/components/Header/Header.tsx
  client/src/pages/Search.tsx
Labels: Refactor, FrontEnd, Feat

#161 Fe/feat/#160 on sale visible
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/assets/logo.png
  client/src/components/Card.tsx
  client/src/components/Carousel/Collection.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Layout/Footer.tsx
  client/src/components/Modals/BuyCoinModal.tsx
  client/src/components/Modals/SellModal.tsx
  client/src/components/Profile/ProfileBio.tsx
  client/src/components/Trending/Top.tsx
  client/src/index.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/pages/SuccessPaymentPage.tsx
Labels: FrontEnd, Feat

#162 Fe/feat/버그 해결 & 리팩토링
  client/public/index.html
  client/src/components/Carousel/Carousel.tsx
  client/src/components/Carousel/Collection.tsx
  client/src/components/Carousel/MainCarousel.tsx
  client/src/components/Carousel/MainCollection.tsx
  client/src/components/CreateItem/CollectionOptions.tsx
  client/src/components/CreateItem/CreateItem.tsx
  client/src/components/Profile/Alert.tsx
  client/src/components/Profile/ProfileBio.tsx
  client/src/components/Profile/ProfileLogo.tsx
  client/src/components/Search/ColResult.tsx
  client/src/components/Search/ColResults.tsx
  client/src/pages/Search.tsx
Labels: Bug, Refactor, FrontEnd

#163 fix: 회원 탈퇴
  client/public/favicon.ico
  client/public/index.html
  client/src/components/Profile/Alert.tsx
  client/src/pages/MainPage.tsx
  client/src/store/toastSlice.ts
  client/src/utils/api/api.ts
Labels: Bug, FrontEnd

#169 Fe/feat/여러가지
  client/src/App.tsx
  client/src/components/Card.tsx
  client/src/components/CreateCollection/BannerImage.tsx
  client/src/components/CreateCollection/LogoImage.tsx
  client/src/components/CreateItem/ItemImage.tsx
  client/src/components/ItemDetail/ItemDetail.tsx
  client/src/components/Layout/Footer.tsx
  client/src/components/Profile/Alert.tsx
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/pages/CreateCollectionPage.tsx
  client/src/pages/CreateItemPage.tsx
  client/src/pages/EditProfile.tsx
  client/src/pages/MyCollection.tsx
  client/src/pages/Search.tsx
  client/src/pages/SuccessPaymentPage.tsx
Labels: Bug, Refactor, FrontEnd, Feat

#170 fix: 다크모드 맞게 수정
  client/src/pages/Search.tsx
Labels: Bug, FrontEnd

#173 env 파일 깃이그노어 추가
  client/.gitignore
  env
Labels: FrontEnd, Chore

#174 chore:ItemDetail.tsx useEffect 의존성 배열추가 및 깃이그노어 수정
  client/src/components/ItemDetail/ItemDetail.tsx
Labels: Bug, FrontEnd
