Repository codestates-seb/seb41_main_008, pull requests merged in 2023-01, with the labels that each got.

#2 FE/feat:headerbar
  client/.eslintrc.json
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/App.tsx
  client/src/components/header/DropdownItems.tsx
  client/src/components/header/Header.tsx
  client/src/index.js
  client/src/index.tsx
  client/tsconfig.json
Labels: enhancement

#13 feat: 전체 도메인 - member/coin/item/transaction/cart 관련 1차 설계 마무리.
  server/src/main/java/com/nfteam/server/ServerApplication.java
  server/src/main/java/com/nfteam/server/ServerTestController.java
  server/src/main/java/com/nfteam/server/audit/AuditingFields.java
  server/src/main/java/com/nfteam/server/audit/BaseEntity.java
  server/src/main/java/com/nfteam/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/nfteam/server/cart/entity/Cart.java
  server/src/main/java/com/nfteam/server/cart/entity/CartItemRel.java
  server/src/main/java/com/nfteam/server/coin/Coin.java
  server/src/main/java/com/nfteam/server/coin/CoinMemberRel.java
  server/src/main/java/com/nfteam/server/config/SecurityConfiguration.java
  server/src/main/java/com/nfteam/server/item/entity/Item.java
  server/src/main/java/com/nfteam/server/item/entity/ItemCollection.java
  server/src/main/java/com/nfteam/server/item/entity/ItemCredential.java
  server/src/main/java/com/nfteam/server/item/entity/ItemPrice.java
  server/src/main/java/com/nfteam/server/member/Repository/MemberRepository.java
  server/src/main/java/com/nfteam/server/member/Service/MemberService.java
  server/src/main/java/com/nfteam/server/member/controller/MemberController.java
  server/src/main/java/com/nfteam/server/member/dto/MemberDto.java
  server/src/main/java/com/nfteam/server/member/dto/Request/MemberRegisterRequest.java
  server/src/main/java/com/nfteam/server/member/dto/Response/MemberExistsCheckResponse.java
  server/src/main/java/com/nfteam/server/member/entity/Member.java
  server/src/main/java/com/nfteam/server/transaction/entity/TransAction.java
  server/src/main/java/com/nfteam/server/transaction/entity/TransType.java
  server/src/main/resources/application-dev.yml
Labels: Refactor, BackEnd, Feat

#14 feat: 로그인,로그아웃 구현을 위한 member api,business 계층 구현
  server/build.gradle
  server/src/main/java/com/nfteam/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/nfteam/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/nfteam/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/nfteam/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/nfteam/server/config/SecurityConfiguration.java
  server/src/main/java/com/nfteam/server/config/WebConfig.java
  server/src/main/java/com/nfteam/server/dto/LoginDto.java
  server/src/main/java/com/nfteam/server/member/controller/MemberController.java
  server/src/main/java/com/nfteam/server/member/dto/MemberPatchDto.java
  server/src/main/java/com/nfteam/server/member/dto/MemberPostDto.java
  server/src/main/java/com/nfteam/server/member/dto/MemberResponseDto.java
  server/src/main/java/com/nfteam/server/member/entity/Member.java
  server/src/main/java/com/nfteam/server/member/mapper/MemberMapper.java
  server/src/main/java/com/nfteam/server/member/repository/MemberRepository.java
  server/src/main/java/com/nfteam/server/member/service/MemberService.java
Labels: Refactor, BackEnd, Feat

#20 feat: nginx 무중단 배포 파일 및 스크립트 입력
  server/appspec.yml
  server/build.gradle
  server/scripts/health.sh
  server/scripts/profile.sh
  server/scripts/start.sh
  server/scripts/stop.sh
  server/scripts/switch.sh
  server/src/main/java/com/nfteam/server/nginx/ProfileController.java
  server/src/main/resources/application-deploy1.yml
  server/src/main/resources/application-deploy2.yml
Labels: BackEnd, Feat

#25 feat: 백엔드 의존성 정리 완료.
  server/build.gradle
Labels: Refactor, BackEnd

#27 test: 개발서버 이미지 업로드 테스트
  server/src/main/java/com/nfteam/server/ServerTestController.java
Labels: Test

#35 feat: 캐러셀 구현과 이미지 로딩속도 개선
  client/.eslintrc.json
  client/src/components/Carousel.tsx
  client/src/components/carousel/Carousel.tsx
  client/src/components/carousel/Collection.tsx
  client/src/components/carousel/MainCarousel.tsx
  client/src/components/carousel/MainCollection.tsx
  client/src/pages/MainPage.tsx
Labels: FrontEnd, Feat

#40 refactor: 로그인 결과값은 별도의 dto 생성 & 액세스 토큰 재발급시 레디스 비교 로직 일부분 수정
  server/src/main/java/com/nfteam/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/nfteam/server/auth/service/AuthService.java
  server/src/main/java/com/nfteam/server/dto/response/auth/LoginResult.java
Labels: Bug, Refactor, BackEnd

#43 Be/feat/#30 member
  server/src/main/java/com/nfteam/server/exception/auth/NotAuthorizedException.java
  server/src/main/java/com/nfteam/server/member/controller/MemberController.java
  server/src/main/java/com/nfteam/server/member/dto/MemberPatchDto.java
  server/src/main/java/com/nfteam/server/member/dto/MemberResponseDto.java
  server/src/main/java/com/nfteam/server/member/entity/Member.java
  server/src/main/java/com/nfteam/server/member/service/MemberService.java
  server/src/main/java/com/nfteam/server/utils/S3ImageUploader.java
  server/src/main/resources/application.yml
Labels: BackEnd, Feat

#44 Backend
  server/src/main/java/com/nfteam/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/nfteam/server/exception/auth/NotAuthorizedException.java
  server/src/main/java/com/nfteam/server/member/controller/MemberController.java
  server/src/main/java/com/nfteam/server/member/dto/MemberPatchDto.java
  server/src/main/java/com/nfteam/server/member/dto/MemberResponseDto.java
  server/src/main/java/com/nfteam/server/member/entity/Member.java
  server/src/main/java/com/nfteam/server/member/service/MemberService.java
  server/src/main/java/com/nfteam/server/utils/S3ImageUploader.java
  server/src/main/resources/application.yml
Labels: Bug, BackEnd

#50 feat: 캐러셀 구현과 이미지 로딩속도 개선
  client/package-lock.json
  client/src/components/header/Header.tsx
Labels: FrontEnd, Feat

#53 Be/hotfix/#52 jwt error fix
  server/src/main/java/com/nfteam/server/ServerTestController.java
  server/src/main/java/com/nfteam/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/nfteam/server/auth/filter/JwtExceptionFilter.java
  server/src/main/java/com/nfteam/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/nfteam/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/nfteam/server/auth/repository/RedisRepository.java
  server/src/main/java/com/nfteam/server/auth/utils/AuthorizationExtractor.java
  server/src/main/java/com/nfteam/server/config/SecurityConfiguration.java
  server/src/main/java/com/nfteam/server/dto/response/auth/LoginResult.java
  server/src/main/java/com/nfteam/server/member/controller/MemberController.java
  server/src/main/java/com/nfteam/server/member/dto/MemberPatchDto.java
  server/src/main/java/com/nfteam/server/member/dto/MemberPostDto.java
  server/src/main/java/com/nfteam/server/member/dto/MemberResponseDto.java
  server/src/main/java/com/nfteam/server/member/entity/Member.java
  server/src/main/java/com/nfteam/server/member/repository/MemberRepository.java
  server/src/main/java/com/nfteam/server/member/service/MemberService.java
  server/src/main/resources/application.yml
Labels: Bug, Refactor, BackEnd, Feat

#54 feat: 2023-01-11 최신 업데이트분까지 백엔드 배포
  server/src/main/java/com/nfteam/server/ServerTestController.java
  server/src/main/java/com/nfteam/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/nfteam/server/auth/filter/JwtExceptionFilter.java
  server/src/main/java/com/nfteam/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/nfteam/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/nfteam/server/auth/repository/RedisRepository.java
  server/src/main/java/com/nfteam/server/auth/utils/AuthorizationExtractor.java
  server/src/main/java/com/nfteam/server/config/SecurityConfiguration.java
  server/src/main/java/com/nfteam/server/dto/response/auth/LoginResult.java
  server/src/main/java/com/nfteam/server/member/controller/MemberController.java
  server/src/main/java/com/nfteam/server/member/dto/MemberPatchDto.java
  server/src/main/java/com/nfteam/server/member/dto/MemberPostDto.java
  server/src/main/java/com/nfteam/server/member/dto/MemberResponseDto.java
  server/src/main/java/com/nfteam/server/member/entity/Member.java
  server/src/main/java/com/nfteam/server/member/repository/MemberRepository.java
  server/src/main/java/com/nfteam/server/member/service/MemberService.java
  server/src/main/resources/application.yml
Labels: BackEnd

#55 fix: 토큰 만료시간 설정 파일 조정
  server/src/main/resources/application-deploy1.yml
  server/src/main/resources/application-deploy2.yml
Labels: Bug

#59 Be/feat/#23 item/transaction
  server/src/main/java/com/nfteam/server/ServerApplication.java
  server/src/main/java/com/nfteam/server/coin/Coin.java
  server/src/main/java/com/nfteam/server/dto/request/item/CollectionCreateRequest.java
  server/src/main/java/com/nfteam/server/dto/request/item/CollectionPatchRequest.java
  server/src/main/java/com/nfteam/server/dto/request/item/ItemCreateRequest.java
  server/src/main/java/com/nfteam/server/dto/request/member/MemberPatchDto.java
  server/src/main/java/com/nfteam/server/dto/request/member/MemberPostDto.java
  server/src/main/java/com/nfteam/server/dto/response/common/SingleIdResponse.java
  server/src/main/java/com/nfteam/server/dto/response/item/CollectionResponse.java
  server/src/main/java/com/nfteam/server/dto/response/item/ItemResponseDto.java
  server/src/main/java/com/nfteam/server/dto/response/item/UserCollectionResponse.java
  server/src/main/java/com/nfteam/server/dto/response/member/MemberResponseDto.java
  server/src/main/java/com/nfteam/server/item/controller/CollectionController.java
  server/src/main/java/com/nfteam/server/item/controller/ItemController.java
  server/src/main/java/com/nfteam/server/item/entity/Item.java
  server/src/main/java/com/nfteam/server/item/entity/ItemCollection.java
  server/src/main/java/com/nfteam/server/item/entity/ItemCredential.java
  server/src/main/java/com/nfteam/server/item/entity/ItemPrice.java
  server/src/main/java/com/nfteam/server/item/repository/CollectionRepository.java
  server/src/main/java/com/nfteam/server/item/repository/ItemCollectionRepository.java
  server/src/main/java/com/nfteam/server/item/repository/ItemRepository.java
  server/src/main/java/com/nfteam/server/item/repository/QItemRepository.java
  server/src/main/java/com/nfteam/server/item/service/CollectionService.java
  server/src/main/java/com/nfteam/server/item/service/ItemService.java
  server/src/main/java/com/nfteam/server/member/controller/MemberController.java
  server/src/main/java/com/nfteam/server/member/mapper/MemberMapper.java
Labels: BackEnd, Feat

#66 Fe/feat/#49 my collections
  client/package-lock.json
  client/package.json
  client/src/components/CreateCollection/BannerImage.tsx
  client/src/components/CreateCollection/Input.tsx
  client/src/components/CreateCollection/LogoImage.tsx
  client/src/components/carousel/Carousel.tsx
  client/src/components/carousel/MainCarousel.tsx
  client/src/index.css
  client/src/pages/CreateCollectionPage.tsx
  client/src/pages/MainPage.tsx
  client/src/store/bannerSlice.ts
  client/src/store/logoSlice.ts
  client/src/store/store.ts
  client/tailwind.config.js
Labels: FrontEnd, Feat

#68 feat: name과 description 보완
  client/src/components/CreateCollection/Input.tsx
  client/src/components/HoverCard/HoverCard.tsx
  client/src/pages/MyCollectionPage.tsx
  client/tailwind.config.js
Labels: FrontEnd, Feat

#71 feat: missing page
  client/src/App.tsx
  client/src/components/CreateCollection/MissingPage/MissingPage.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/pages/MyCollectionPage.tsx
Labels: FrontEnd, Feat

#76 Fe/feat/#49 my collections
  client/src/App.tsx
  client/src/components/CreateCollection/BannerImage.tsx
  client/src/components/CreateCollection/Input.tsx
  client/src/components/CreateCollection/LogoImage.tsx
  client/src/components/MissingPage/MissingPage.tsx
  client/src/components/Trending/Carousel.tsx
  client/src/components/Trending/Top.tsx
  client/src/pages/CreateCollectionPage.tsx
  client/src/pages/MainPage.tsx
  client/src/store/bannerSlice.ts
  client/src/store/logoSlice.ts
Labels: FrontEnd, Feat

#82 Be/feat/#65 colletion item - transaction 단일 상품 기록 및 다중 상품 기록 api 개발 완료.
  server/src/main/java/com/nfteam/server/cart/controller/CartController.java
  server/src/main/java/com/nfteam/server/dto/request/transaction/TransActionCreateRequest.java
  server/src/main/java/com/nfteam/server/item/entity/Item.java
  server/src/main/java/com/nfteam/server/item/entity/ItemCredential.java
  server/src/main/java/com/nfteam/server/item/repository/ItemCollectionRepository.java
  server/src/main/java/com/nfteam/server/item/repository/ItemCredentialRepository.java
  server/src/main/java/com/nfteam/server/item/service/CollectionService.java
  server/src/main/java/com/nfteam/server/item/service/ItemService.java
  server/src/main/java/com/nfteam/server/transaction/controller/TransActionController.java
  server/src/main/java/com/nfteam/server/transaction/entity/TransAction.java
  server/src/main/java/com/nfteam/server/transaction/service/TransActionService.java
Labels: BackEnd, Feat

#86 FE/feat/#80-Mypage
  client/.env
  client/src/components/Card.tsx
  client/src/components/CartButton/BuyAndCartButton.tsx
  client/src/components/CreateCollection/LogoImage.tsx
  client/src/components/LoginAndSignup/InputContainer.tsx
  client/src/components/Oauth2.0/GoogleLoginButton.tsx
  client/src/components/header/Header.tsx
  client/src/components/header/MobileDropdown.tsx
  client/src/components/header/MobileDropdownItems.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/MainPage.tsx
  client/src/store/loginSlice.tsx
  client/src/store/oauthSlice.ts
  client/src/store/signupSlice.tsx
  client/src/store/store.ts
  client/src/utils/api/api.ts
  client/src/utils/api/axios.ts
  client/src/utils/token.ts
Labels: FrontEnd, Feat

#89 FE/refactor/#88 refactor
  client/src/App.tsx
  client/src/components/Account/NoCard.tsx
  client/src/components/CartingModal/CartingModal.tsx
  client/src/components/ItemDetail/Buy.sass
  client/src/components/ItemDetail/CountDownTime/CountDown.module.css
  client/src/components/ItemDetail/CountDownTime/CountDown.tsx
  client/src/components/ItemDetail/ItemDetail.tsx
  client/src/components/ItemDetail/data.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/components/Purchase/Button/BuyAndCartButton.tsx
  client/src/components/Purchase/Button/BuynowButton.tsx
  client/src/components/Purchase/Button/CartButton.tsx
  client/src/components/Purchase/Buy.tsx
  client/src/components/Purchase/index.ts
  client/src/components/Trending/Top.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/ItemDetailPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/Purchase.tsx
  client/src/utils/api/api.ts
Labels: Refactor, FrontEnd

#91 feat: 컬렉션 상세 페이지 구현, Card 컴포넌트 수정
  client/package-lock.json
  client/package.json
  client/src/components/Card.tsx
  client/src/components/CartButton/BuynowButton.tsx
  client/src/components/CartButton/CartButton.tsx
  client/src/components/DropdownMenu/DropdownMenu.tsx
  client/src/components/header/Dropdown.tsx
  client/src/components/header/Header.tsx
  client/src/index.css
  client/src/pages/CollectionDetails.tsx
  client/src/pages/MainPage.tsx
  client/tsconfig.json
Labels: FrontEnd, Feat

#92 feat:장바구니 담기기능 추가
  client/src/components/CartButton/BuyAndCartButton.tsx
  client/src/components/CartButton/BuynowButton.tsx
  client/src/components/CartButton/CartButton.tsx
  client/src/components/CartingModal/CartItems.tsx
  client/src/components/CartingModal/CartingModal.tsx
  client/src/components/ItemDetail/ItemDetail.tsx
  client/src/pages/AccountPage.tsx
  client/src/store/cartSlice.ts
  client/src/store/store.ts
  client/src/utils/api/api.ts
Labels: FrontEnd, Feat

#93 feat: 아이템 수정하기 -> 아이템 판매하기 방식으로 api 변경
  server/src/main/java/com/nfteam/server/dto/request/item/ItemCreateRequest.java
  server/src/main/java/com/nfteam/server/dto/request/item/ItemPatchRequest.java
  server/src/main/java/com/nfteam/server/dto/request/item/ItemSellRequest.java
  server/src/main/java/com/nfteam/server/dto/response/item/ItemResponse.java
  server/src/main/java/com/nfteam/server/item/controller/ItemController.java
  server/src/main/java/com/nfteam/server/item/entity/Item.java
  server/src/main/java/com/nfteam/server/item/service/ItemService.java
Labels: BackEnd, Feat

#95 refactor:헤더바 불필요한 드랍다운 삭제 및 리팩토링
  client/src/components/Card.tsx
  client/src/components/CartButton/BuyAndCartButton.tsx
  client/src/components/CartingModal/CartingModal.tsx
  client/src/components/ItemDetail/ItemDetail.tsx
  client/src/components/header/Dropdown.tsx
  client/src/components/header/DropdownItems.tsx
  client/src/components/header/Header.tsx
  client/src/components/header/MobileDropdown.tsx
  client/src/components/header/MobileDropdownItems.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/store/cartSlice.ts
  client/src/utils/api/api.ts
Labels: Refactor, FrontEnd

#99 feat: 거래 api 개발 완료.
  server/src/main/java/com/nfteam/server/dto/request/transaction/TransActionCreateRequest.java
  server/src/main/java/com/nfteam/server/dto/request/transaction/TransActionRequestItemInfo.java
  server/src/main/java/com/nfteam/server/exception/ExceptionCode.java
  server/src/main/java/com/nfteam/server/exception/coin/CoinNotFoundException.java
  server/src/main/java/com/nfteam/server/item/repository/ItemRepository.java
  server/src/main/java/com/nfteam/server/transaction/controller/TransActionController.java
  server/src/main/java/com/nfteam/server/transaction/service/TransActionService.java
  server/src/main/resources/application.yml
Labels: BackEnd

#101 FE/feat/#90 cart2
  client/.env
  client/package-lock.json
  client/package.json
  client/src/components/Card.tsx
  client/src/components/CartButton/BuyAndCartButton.tsx
  client/src/components/CartingModal/CartItems.tsx
  client/src/components/CartingModal/CartingModal.tsx
  client/src/components/CartingModal/SellModal.tsx
  client/src/components/ItemDetail/ItemDetail.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/components/LoginAndSignup/InputContainer.tsx
  client/src/components/header/Dropdown.tsx
  client/src/components/header/DropdownItems.tsx
  client/src/components/header/MobileDropdown.tsx
  client/src/components/header/MobileDropdownItems.tsx
  client/src/index.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/store/cartSlice.ts
  client/src/store/modalSlice.tsx
  client/src/store/store.ts
  client/src/utils/api/api.ts
Labels: FrontEnd, Feat

#102 Be/refactor/collection read
  server/src/main/java/com/nfteam/server/dto/response/common/PageInfo.java
  server/src/main/java/com/nfteam/server/dto/response/common/PageResponse.java
  server/src/main/java/com/nfteam/server/dto/response/item/CollectionOnlyResponse.java
  server/src/main/java/com/nfteam/server/item/controller/CollectionController.java
  server/src/main/java/com/nfteam/server/item/controller/ItemController.java
  server/src/main/java/com/nfteam/server/item/repository/QItemRepository.java
  server/src/main/java/com/nfteam/server/item/service/CollectionService.java
  server/src/main/java/com/nfteam/server/item/service/ItemService.java
Labels: Refactor, BackEnd, Feat

#103 Be/feat/#100 ranking - 랭킹 조회 api 개발 완료.
  server/src/main/java/com/nfteam/server/ServerApplication.java
  server/src/main/java/com/nfteam/server/batch/entity/TimeRankingEntity.java
  server/src/main/java/com/nfteam/server/batch/job/TransAction1DReaderJobConfiguration.java
  server/src/main/java/com/nfteam/server/batch/job/TransAction1MReaderJobConfiguration.java
  server/src/main/java/com/nfteam/server/batch/job/TransAction1WReaderJobConfiguration.java
  server/src/main/java/com/nfteam/server/batch/repository/TimeRankingRepository.java
  server/src/main/java/com/nfteam/server/batch/scheduler/TransActionCoinRankingReaderJobScheduler.java
  server/src/main/java/com/nfteam/server/batch/scheduler/TransActionTimeRankingReaderJobScheduler.java
  server/src/main/java/com/nfteam/server/common/config/CacheConfig.java
  server/src/main/java/com/nfteam/server/common/config/RedisConfiguration.java
  server/src/main/java/com/nfteam/server/dto/request/ranking/RankingListRequest.java
  server/src/main/java/com/nfteam/server/dto/response/ranking/RankingResponse.java
  server/src/main/java/com/nfteam/server/exception/ExceptionCode.java
  server/src/main/java/com/nfteam/server/exception/ranking/RankCoinCriteriaNotValidException.java
  server/src/main/java/com/nfteam/server/exception/ranking/RankTimeCriteriaNotValidException.java
  server/src/main/java/com/nfteam/server/item/repository/ItemRepository.java
  server/src/main/java/com/nfteam/server/ranking/controller/RankingController.java
  server/src/main/java/com/nfteam/server/ranking/repository/QRankingRepository.java
  server/src/main/java/com/nfteam/server/ranking/service/RankingService.java
  server/src/main/resources/application.yml
Labels: Refactor, BackEnd, Feat

#104 feat: 아이템 상세 조회 시 거래 히스토리 / 가격 히스토리 추가
  server/src/main/java/com/nfteam/server/dto/response/item/ItemPriceHistoryResponse.java
  server/src/main/java/com/nfteam/server/dto/response/item/ItemTradeHistoryResponse.java
  server/src/main/java/com/nfteam/server/item/service/ItemService.java
  server/src/main/java/com/nfteam/server/transaction/repository/QTransActionRepository.java
Labels: BackEnd, Feat

#106 Fe/feat/#49 feat: 컬렉션 생성/조회, 아이템 생성
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Card.tsx
  client/src/components/CreateCollection/BannerImage.tsx
  client/src/components/CreateCollection/CollectionModal.tsx
  client/src/components/CreateCollection/CreateCollection.tsx
  client/src/components/CreateCollection/LogoImage.tsx
  client/src/components/CreateCollection/RadioButtons.tsx
  client/src/components/CreateItem/CollectionOptions.tsx
  client/src/components/CreateItem/CreateItem.tsx
  client/src/components/CreateItem/ItemImage.tsx
  client/src/components/CreateItem/ItemModal.tsx
  client/src/components/MyCollection/Cards.tsx
  client/src/components/MyCollection/DropMenu.tsx
  client/src/components/MyCollection/HoverCard.tsx
  client/src/components/header/DropdownItems.tsx
  client/src/index.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/pages/CreateCollectionPage.tsx
  client/src/pages/CreateItemPage.tsx
  client/src/pages/MissingPage.tsx
  client/src/pages/MyCollection.tsx
Labels: FrontEnd, Feat

#109 Be/feat/#108 search 검색기능 개발 완료.
  server/src/main/java/com/nfteam/server/dto/response/search/SearchCollectionResponse.java
  server/src/main/java/com/nfteam/server/dto/response/search/SearchItemResponse.java
  server/src/main/java/com/nfteam/server/dto/response/search/SearchResponse.java
  server/src/main/java/com/nfteam/server/item/controller/SearchController.java
  server/src/main/java/com/nfteam/server/item/repository/QSearchRepository.java
  server/src/main/java/com/nfteam/server/item/service/SearchService.java
Labels: BackEnd, Feat

#112 feat:결제 기능 구현
  client/src/components/Card.tsx
  client/src/components/CartButton/BuyAndCartButton.tsx
  client/src/components/CartingModal/CartingModal.tsx
  client/src/components/CartingModal/SellModal.tsx
  client/src/components/CartingModal/TransActionModal.tsx
  client/src/components/CartingModal/WalletModal.tsx
  client/src/components/ItemDetail/ItemDetail.tsx
  client/src/components/LoginAndSignup/GoogleLoginButton.tsx
  client/src/components/LoginAndSignup/InputContainer.tsx
  client/src/components/header/Dropdown.tsx
  client/src/components/header/DropdownItems.tsx
  client/src/components/header/Header.tsx
  client/src/components/header/MobileDropdownItems.tsx
  client/src/index.tsx
  client/src/pages/MyCollection.tsx
  client/src/store/cartSlice.ts
  client/src/store/loginSlice.tsx
  client/src/store/modalSlice.tsx
  client/src/utils/api/api.ts
Labels: FrontEnd, Feat

#123 FE/feat/#113 wallet,payment
  client/src/components/Card.tsx
  client/src/components/CartButton/BuyAndCartButton.tsx
  client/src/components/CartingModal/BuyCoinModal.tsx
  client/src/components/CartingModal/CartItems.tsx
  client/src/components/CartingModal/CartingModal.tsx
  client/src/components/CartingModal/SellModal.tsx
  client/src/components/CartingModal/TransActionModal.tsx
  client/src/components/CartingModal/WalletModal.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/components/LoginAndSignup/InputContainer.tsx
  client/src/pages/MyCollection.tsx
  client/src/store/modalSlice.tsx
  client/src/utils/api/api.ts
Labels: FrontEnd, Feat

#124 Fe/feat/#49 회원탈퇴 및 토스트별 state, action 작성
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Carousel/Carousel.tsx
  client/src/components/Carousel/MainCarousel.tsx
  client/src/components/CreateCollection/BannerImage.tsx
  client/src/components/CreateCollection/CreateCollection.tsx
  client/src/components/CreateCollection/LogoImage.tsx
  client/src/components/CreateItem/CreateItem.tsx
  client/src/components/CreateItem/ItemImage.tsx
  client/src/components/Header/Dropdown.tsx
  client/src/components/MyCollection/MintDropdown.tsx
  client/src/components/Notification.tsx
  client/src/components/Profile/Alert.tsx
  client/src/components/Profile/ProfileBanner.tsx
  client/src/components/Profile/ProfileBio.tsx
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/components/Profile/ProfileLogo.tsx
  client/src/index.css
  client/src/pages/AccountPage.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/MyAccount.tsx
  client/src/pages/MyCollection.tsx
  client/src/pages/ProfilePage.tsx
  client/src/store/toastSlice.ts
  client/src/utils/api/api.ts
Labels: FrontEnd, Feat

#126 Be/refactor/refactoring all
  server/src/main/java/com/nfteam/server/cart/service/CartService.java
  server/src/main/java/com/nfteam/server/coin/controller/CoinController.java
  server/src/main/java/com/nfteam/server/common/config/WebConfig.java
  server/src/main/java/com/nfteam/server/common/utils/PageableArgumentResolver.java
  server/src/main/java/com/nfteam/server/common/utils/UriCheckInterceptor.java
  server/src/main/java/com/nfteam/server/dto/response/coin/CoinPurchaseApproveResponse.java
  server/src/main/java/com/nfteam/server/dto/response/coin/CoinPurchaseReadyResponse.java
  server/src/main/java/com/nfteam/server/dto/response/coin/CoinResponse.java
  server/src/main/java/com/nfteam/server/exception/ExceptionCode.java
  server/src/main/java/com/nfteam/server/exception/support/PageParameterInvalidException.java
  server/src/main/java/com/nfteam/server/exception/support/UrlLengthInvalidException.java
  server/src/main/java/com/nfteam/server/item/controller/ItemController.java
  server/src/main/java/com/nfteam/server/item/controller/SearchController.java
  server/src/main/java/com/nfteam/server/item/repository/ItemRepository.java
  server/src/main/java/com/nfteam/server/item/repository/ItemRepositoryCustom.java
  server/src/main/java/com/nfteam/server/item/repository/ItemRepositoryCustomImpl.java
  server/src/main/java/com/nfteam/server/item/service/ItemService.java
  server/src/main/java/com/nfteam/server/item/service/SearchService.java
  server/src/main/java/com/nfteam/server/member/entity/Member.java
  server/src/main/java/com/nfteam/server/member/repository/MemberRepository.java
Labels: Refactor, BackEnd, Feat

#127 Fe/feat/#113 wallet,payment
  client/package-lock.json
  client/src/App.tsx
  client/src/assets/kakaopayM.png
  client/src/assets/kakaopayS.png
  client/src/components/Card.tsx
  client/src/components/CartButton/BuyAndCartButton.tsx
  client/src/components/CartingModal/BuyCoinModal.tsx
  client/src/components/CartingModal/CartItems.tsx
  client/src/components/CartingModal/CartingModal.tsx
  client/src/components/CartingModal/SellModal.tsx
  client/src/components/CartingModal/TransActionModal.tsx
  client/src/components/CartingModal/WalletModal.tsx
  client/src/components/CreateCollection/CollectionModal.tsx
  client/src/components/Header/Dropdown.tsx
  client/src/components/Header/DropdownItems.tsx
  client/src/components/ItemDetail/ItemDetail.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/components/LoginAndSignup/InputContainer.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/SuccessPaymentPage.tsx
  client/src/store/loginSlice.tsx
  client/src/utils/ScrollToTop.ts
  client/src/utils/api/api.ts
Labels: FrontEnd, Feat

#132 Be/refactor/add feat - 조회시 코인 이미지 추가
  server/src/main/java/com/nfteam/server/domain/item/entity/ItemCollection.java
  server/src/main/java/com/nfteam/server/domain/item/repository/ItemRepositoryCustomImpl.java
  server/src/main/java/com/nfteam/server/domain/ranking/repository/QRankingRepository.java
  server/src/main/java/com/nfteam/server/dto/response/item/ItemResponse.java
  server/src/main/java/com/nfteam/server/dto/response/member/MemberCollectionResponse.java
  server/src/main/java/com/nfteam/server/dto/response/member/MemberItemResponse.java
  server/src/main/java/com/nfteam/server/dto/response/ranking/RankingResponse.java
Labels: BackEnd, Feat

#133 refactor: 컬렉션 정보 조회시 코인 이미지 추가
  server/src/main/java/com/nfteam/server/domain/item/entity/ItemCollection.java
  server/src/main/java/com/nfteam/server/dto/response/item/CollectionItemResponse.java
  server/src/main/java/com/nfteam/server/dto/response/item/CollectionResponse.java
Labels: BackEnd, Feat

#134 Fe/feat: 홈페이지 배경색, 프로필 수정 권한, 컬렉션 상세 페이지, 404 페이지
  .vscode/settings.json
  client/src/App.tsx
  client/src/components/Card.tsx
  client/src/components/CartButton/BuyAndCartButton.tsx
  client/src/components/CreateCollection/CollectionModal.tsx
  client/src/components/CreateItem/CollectionOptions.tsx
  client/src/components/CreateItem/CreateItem.tsx
  client/src/components/CreateItem/ItemModal.tsx
  client/src/components/Header/Dropdown.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Header/MainDropdown.tsx
  client/src/components/Header/MainHeader.tsx
  client/src/components/ItemCard.tsx
  client/src/components/ItemDetail/ItemDetail.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/components/MyCollection/Cards.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/CollectionDetails.tsx
  client/src/pages/CreateItemPage.tsx
  client/src/pages/ItemDetailPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/MissingPage.tsx
  client/src/pages/MyAccount.tsx
  client/src/pages/MyCollection.tsx
  client/src/pages/ProfilePage.tsx
  client/src/pages/SuccessPaymentPage.tsx
Labels: FrontEnd, Feat

#135 chore: 아이템 상세 페이지 수정
  client/src/components/ItemDetail/ItemDetail.tsx
Labels: FrontEnd, Chore

#138 feat:카카오페이 결제성공 페이지구현
  client/src/App.tsx
  client/src/components/Card.tsx
  client/src/components/CartButton/BuyAndCartButton.tsx
  client/src/components/Header/DropdownItems.tsx
  client/src/components/Header/Header.tsx
  client/src/components/ItemDetail/ItemDetail copy.tsx
  client/src/components/ItemDetail/ItemDetail.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/components/LoginAndSignup/InputContainer.tsx
  client/src/components/Modals/BuyCoinModal.tsx
  client/src/components/Modals/TransActionModal.tsx
  client/src/components/MyCollection/Cards.tsx
  client/src/pages/AccountPage.tsx
  client/src/pages/SuccessPaymentPage.tsx
  client/src/store/toastSlice.ts
  client/src/utils/api/api.ts
Labels: FrontEnd, Feat
